# Generated by Django 4.2.7 on 2023-11-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilge_dice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rolls',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
