# Generated by Django 4.2.7 on 2023-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilge_dice', '0002_game_rolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstate',
            name='is_game_over',
            field=models.BooleanField(default=False),
        ),
    ]
