# Generated by Django 4.2.7 on 2023-11-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilge_dice', '0003_playerstate_is_game_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstate',
            name='rolls_left',
            field=models.IntegerField(default=6),
        ),
    ]
