# Generated by Django 4.2.7 on 2023-11-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilge_dice', '0004_playerstate_rolls_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_sad',
            field=models.FileField(blank=True, upload_to='bilgedice_images/'),
        ),
    ]
