# Generated by Django 4.2.7 on 2023-11-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilge_dice', '0005_player_image_sad'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bet',
            field=models.IntegerField(default=10),
        ),
    ]
