# Generated by Django 4.2.7 on 2023-11-13 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilge_dice', '0006_game_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBilgeDice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_streak', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bilge_dice.user')),
            ],
        ),
    ]
