# Generated by Django 4.2.7 on 2023-11-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilge_dice', '0007_userbilgedice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nps',
            field=models.IntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bilge_dice.user')),
            ],
        ),
    ]
